spring:
  application:
    name: CIQDashboard-alm-collector
  data:
    mongodb:
      uri:
      credents:
      collection:
        assets:

logging:
  level:
    com.cognizant.collector.alm.client.AlmClient:

  pattern:
    console:

scheduler:
  cron:
  enable:

almServer:
  url:
  username:
  password:

server:
  port:

jasypt:
  encryptor:
    password:
    bean:
